spring.application.name=Task1-SpringDataJpa-PostgreSQL


spring.datasource.username=postgres
spring.datasource.password=satorugod1
spring.datasource.url=jdbc:postgresql://db:5432/Tech
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8080
