spring.application.name=Task1-SpringDataJpa-PostgreSQL
server.port=8083


spring.datasource.username=postgres
spring.datasource.password=satorugod1
spring.datasource.url=jdbc:postgresql://localhost:5432/Tech
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
